parameters:
- name: orgUrl
  type: string
- name: projectName
  type: string
- name: repo
  type: string
- name: serviceConnection
  type: string
- name: solutionName
  type: string
- name: configurationData
  type: string
- name: useDeploymentSettingsPlaceholders
  type: string
  default: 'true'

steps:
- powershell: |
      # load PowerShell files into memory
      . "$env:POWERSHELLPATH/update-deployment-settings.ps1"

      # We need the project and repository where the yaml for this pipeline exists.
      # We can get the repository name from $(Build.Repository.Name) and $(System.TeamProject). However, there are situations where we need to override this
      # We've included the ability to set variables to override this parsing (i.e. PipelineProject and PipelineRepository)
      # These can be set as global variables in the alm-accelerator-variable-group.

      # Default to pipeline project and repo to the project where the pipeline is running and the and repo of this yaml
      $pipelineProject = "$(System.TeamProject)"
      $pipelineRepo = "$(Build.Repository.Name)"

      # Use the override variables to bypass the options above
      if(!'$(PipelineProject)'.StartsWith("`$(")) {
        $pipelineProject = "$(PipelineProject)"
      }
      if(!'$(PipelineRepository)'.StartsWith("`$(")) {
        $pipelineRepo = "$(PipelineRepository)"
      }

      #Call the deployment settings powershell
      Set-DeploymentSettingsConfiguration '$(Build.SourcesDirectory)' '$(Agent.BuildDirectory)\PipelineUtils' "$pipelineProject" "$pipelineRepo" '$(connectionVariables.BuildTools.DataverseConnectionString)' '$(XrmDataPowerShellVersion)' '$(CoETools_Microsoft_Xrm_Data_PowerShell)' '${{parameters.orgUrl}}' '${{parameters.projectName}}' '${{parameters.repo}}' 'Bearer' '${{parameters.serviceConnection}}' '${{parameters.solutionName}}' '$(Agent.OS)' '${{parameters.useDeploymentSettingsPlaceholders}}'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    DEPLOYMENT_SETTINGS: ${{parameters.configurationData}}
  displayName: 'Update Deployment Settings'
  condition: and(succeeded(), ne(variables.GenerateDeploymentSettings, 'false'))
